apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eureka-server"
  labels:
    app: "eureka-server"
spec:
  selector:
    matchLabels:
      app: "eureka-server"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "eureka-server"
    spec:
      containers:
        - name: "eureka-server"
          image: nidhinalungal/eureka
          ports:
            - containerPort: 8761
              name: "eureka-server"

---

apiVersion: v1
kind: Service
metadata:
  name: "eureka-server"
spec:
  selector:
    app: "eureka-server"
  type: LoadBalancer
  ports:
    - name: "eureka-server"
      protocol: TCP
      port: 8761
      targetPort: 8761
